version: '3'
services:
  mysql-low-memory:
    image: hsheth2/mysql-low-memory:latest
    environment:
      - MYSQL_ROOT_PASSWORD=gogo
  random-chat:
    image: xdudin/random-chat:alfa-0.1
    ports:
      - 8080:8080
    environment:
      - spring.sql.init.mode=always
      - connection_root=mysql-low-memory
      - spring.datasource.password=gogo
    restart: on-failure
