version: '3'

# called with env-file option
# docker compose -f compose_mysql_local.yaml --env-file ./secrets/db_passwords.env up -p

services:
  mysql-low-memory-local:
    image: hsheth2/mysql-low-memory:8.0.30-oracle
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: messenger_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - mysql_storage:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_storage:
    external: true
