-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 20:02:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema messenger_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `messenger_db`;

-- -----------------------------------------------------
-- Schema messenger_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `messenger_db`;
USE `messenger_db`;

-- -----------------------------------------------------
-- Table `messenger_db`.`age_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`age_group`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`age_group`
(
    `id`  TINYINT(1) UNSIGNED NOT NULL,
    `age` CHAR(5)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `age_group_UNIQUE` (`age` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`gender`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`gender`
(
    `id`     TINYINT(1) UNSIGNED NOT NULL,
    `gender` CHAR(6)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `gender_UNIQUE` (`gender` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`language`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`language`
(
    `id`   TINYINT(1) UNSIGNED NOT NULL,
    `name` VARCHAR(32)         NOT NULL,
    `code` CHAR(2)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`user`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`user`
(
    `id`          INT UNSIGNED        NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(30)         NOT NULL,
    `language_id` TINYINT(1) UNSIGNED NOT NULL,
    `gender_id`   TINYINT(1) UNSIGNED NULL,
    `age_id`      TINYINT(1) UNSIGNED NULL,
    `password`    BINARY(60)          NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `age_fk_idx` (`age_id` ASC) VISIBLE,
    INDEX `gender_fk_idx` (`gender_id` ASC) VISIBLE,
    INDEX `language_fk_idx` (`language_id` ASC) VISIBLE,
    CONSTRAINT `age_fk`
        FOREIGN KEY (`age_id`)
            REFERENCES `messenger_db`.`age_group` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `gender_fk`
        FOREIGN KEY (`gender_id`)
            REFERENCES `messenger_db`.`gender` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `language_fk`
        FOREIGN KEY (`language_id`)
            REFERENCES `messenger_db`.`language` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_type`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_type`
(
    `id`   TINYINT(1) UNSIGNED NOT NULL,
    `name` CHAR(32)            NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog`
(
    `id`      INT UNSIGNED        NOT NULL AUTO_INCREMENT,
    `type_id` TINYINT(1) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `type_id_fk_idx` (`type_id` ASC) VISIBLE,
    CONSTRAINT `type_id_fk`
        FOREIGN KEY (`type_id`)
            REFERENCES `messenger_db`.`dialog_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog_participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_participant`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_participant`
(
    `dialog_id` INT UNSIGNED NOT NULL,
    `user_id`   INT UNSIGNED NOT NULL,
    INDEX `user_id_fk_dp_idx` (`user_id` ASC) VISIBLE,
    INDEX `dialog_id_fk_dp_idx` (`dialog_id` ASC) VISIBLE,
    PRIMARY KEY (`user_id`, `dialog_id`),
    CONSTRAINT `dialog_id_fk_dp`
        FOREIGN KEY (`dialog_id`)
            REFERENCES `messenger_db`.`dialog` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `user_id_fk_dp`
        FOREIGN KEY (`user_id`)
            REFERENCES `messenger_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`message`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`message`
(
    `id`         INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `dialog_id`  INT UNSIGNED  NOT NULL,
    `user_id`    INT UNSIGNED  NOT NULL,
    `created_at` TIMESTAMP     NOT NULL,
    `content`    VARCHAR(4094) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `user_id_fk_idx` (`user_id` ASC) VISIBLE,
    INDEX `dialog_id_fk_idx` (`dialog_id` ASC) VISIBLE,
    CONSTRAINT `dialog_id_fk_msg`
        FOREIGN KEY (`dialog_id`)
            REFERENCES `messenger_db`.`dialog_participant` (`dialog_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `user_id_fk_msg`
        FOREIGN KEY (`user_id`)
            REFERENCES `messenger_db`.`dialog_participant` (`user_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

USE `messenger_db`;

-- -----------------------------------------------------
-- Placeholder table for view `messenger_db`.`user_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_db`.`user_view`
(
    `id`     INT,
    `name`   INT,
    `age`    INT,
    `gender` INT,
    `code`   INT
);

-- -----------------------------------------------------
-- Placeholder table for view `messenger_db`.`dialog_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_view`
(
    `id`   INT,
    `name` INT
);

-- -----------------------------------------------------
-- View `messenger_db`.`user_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`user_view`;
DROP VIEW IF EXISTS `messenger_db`.`user_view`;
USE `messenger_db`;
create OR REPLACE view user_view as
select u.id, u.name, a.age, g.gender, l.code
from messenger_db.user as u
         join messenger_db.language as l
              on u.language_id = l.id
         left outer join messenger_db.age_group as a
                         on u.age_id = a.id
         left outer join messenger_db.gender as g
                         on u.gender_id = g.id;

-- -----------------------------------------------------
-- View `messenger_db`.`dialog_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_view`;
DROP VIEW IF EXISTS `messenger_db`.`dialog_view`;
USE `messenger_db`;
create OR REPLACE view dialog_view as
select d.id, dt.name
from messenger_db.dialog as d
         join messenger_db.dialog_type as dt
              on d.type_id = dt.id;

-- -----------------------------------------------------
-- Fill categories
-- -----------------------------------------------------
INSERT INTO `messenger_db`.`language`
VALUES (1, 'English', 'en');
INSERT INTO `messenger_db`.`language`
VALUES (94, 'Russian', 'ru');
INSERT INTO `messenger_db`.`language`
VALUES (23, 'German', 'de');
INSERT INTO `messenger_db`.`language`
VALUES (34, 'French', 'fr');
INSERT INTO `messenger_db`.`language`
VALUES (51, 'Italian', 'it');
INSERT INTO `messenger_db`.`language`
VALUES (20, 'Czech', 'cs');

INSERT INTO `messenger_db`.`gender`
VALUES (1, 'male');
INSERT INTO `messenger_db`.`gender`
VALUES (2, 'female');

INSERT INTO `messenger_db`.`age_group`
VALUES (1, '14-18');
INSERT INTO `messenger_db`.`age_group`
VALUES (2, '16-20');
INSERT INTO `messenger_db`.`age_group`
VALUES (3, '18-24');
INSERT INTO `messenger_db`.`age_group`
VALUES (4, '22-26');
INSERT INTO `messenger_db`.`age_group`
VALUES (5, '24-30');
INSERT INTO `messenger_db`.`age_group`
VALUES (6, '30+');

INSERT INTO `messenger_db`.`dialog_type`
VALUES (1, 'normal');
INSERT INTO `messenger_db`.`dialog_type`
VALUES (2, 'flirtation');
INSERT INTO `messenger_db`.`dialog_type`
VALUES (3, 'language');

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
