-- MySQL Script generated by MySQL Workbench
-- Tue 19 Jul 2022 01:35:25 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema messenger_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `messenger_db`;

-- -----------------------------------------------------
-- Schema messenger_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `messenger_db`;
USE `messenger_db`;

-- -----------------------------------------------------
-- Table `messenger_db`.`age_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`age_group`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`age_group`
(
    `id`  TINYINT(1) UNSIGNED NOT NULL,
    `age` CHAR(5)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `age_group_UNIQUE` (`age` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`gender`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`gender`
(
    `id`     TINYINT(1) UNSIGNED NOT NULL,
    `gender` CHAR(6)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `gender_UNIQUE` (`gender` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`language`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`language`
(
    `id`   TINYINT(1) UNSIGNED NOT NULL,
    `name` CHAR(32)            NOT NULL,
    `code` CHAR(2)             NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `code_UNIQUE` (`code` ASC),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`user`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`user`
(
    `uuid`        BINARY(16)          NOT NULL,
    `name`        VARCHAR(30)         NOT NULL,
    `age_id`      TINYINT(1) UNSIGNED NULL,
    `gender_id`   TINYINT(1) UNSIGNED NULL,
    `language_id` TINYINT(1) UNSIGNED NOT NULL,
    PRIMARY KEY (`uuid`),
    INDEX `age_fk_idx` (`age_id` ASC),
    INDEX `gender_fk_idx` (`gender_id` ASC),
    INDEX `language_fk_idx` (`language_id` ASC),
    CONSTRAINT `age_fk`
        FOREIGN KEY (`age_id`)
            REFERENCES `messenger_db`.`age_group` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `gender_fk`
        FOREIGN KEY (`gender_id`)
            REFERENCES `messenger_db`.`gender` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `language_fk`
        FOREIGN KEY (`language_id`)
            REFERENCES `messenger_db`.`language` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_type`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_type`
(
    `id`   TINYINT(1) UNSIGNED NOT NULL,
    `name` CHAR(32)            NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog`
(
    `uuid`    BINARY(16)          NOT NULL,
    `type_id` TINYINT(1) UNSIGNED NOT NULL,
    PRIMARY KEY (`uuid`),
    INDEX `type_id_fk_idx` (`type_id` ASC),
    CONSTRAINT `type_id_fk`
        FOREIGN KEY (`type_id`)
            REFERENCES `messenger_db`.`dialog_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`dialog_participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_participant`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_participant`
(
    `dialog_uuid` BINARY(16) NOT NULL,
    `user_uuid`   BINARY(16) NOT NULL,
    INDEX `user_id_fk_dp_idx` (`user_uuid` ASC),
    INDEX `dialog_id_fk_dp_idx` (`dialog_uuid` ASC),
    PRIMARY KEY (`dialog_uuid`, `user_uuid`),
    CONSTRAINT `dialog_id_fk_dp`
        FOREIGN KEY (`dialog_uuid`)
            REFERENCES `messenger_db`.`dialog` (`uuid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `user_id_fk_dp`
        FOREIGN KEY (`user_uuid`)
            REFERENCES `messenger_db`.`user` (`uuid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`message`;

CREATE TABLE IF NOT EXISTS `messenger_db`.`message`
(
    `id`          INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `dialog_uuid` BINARY(16)    NOT NULL,
    `user_uuid`   BINARY(16)    NOT NULL,
    `created_at`  TIMESTAMP     NOT NULL,
    `content`     VARCHAR(4094) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `user_id_fk_idx` (`user_uuid` ASC),
    INDEX `dialog_id_fk_idx` (`dialog_uuid` ASC),
    CONSTRAINT `dialog_id_fk_msg`
        FOREIGN KEY (`dialog_uuid`)
            REFERENCES `messenger_db`.`dialog_participant` (`dialog_uuid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `user_id_fk_msg`
        FOREIGN KEY (`user_uuid`)
            REFERENCES `messenger_db`.`dialog_participant` (`user_uuid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

USE `messenger_db`;

-- -----------------------------------------------------
-- Placeholder table for view `messenger_db`.`user_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_db`.`user_view`
(
    `bin_to_uuid(u.uuid)` INT,
    `name`                INT,
    `age`                 INT,
    `gender`              INT,
    `code`                INT
);

-- -----------------------------------------------------
-- Placeholder table for view `messenger_db`.`dialog_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_view`
(
    `bin_to_uuid(d.uuid)` INT,
    `name`                INT
);

-- -----------------------------------------------------
-- Placeholder table for view `messenger_db`.`dialog_participant_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_db`.`dialog_participant_view`
(
    `dialog_uuid` INT,
    `user_uuid`   INT
);

-- -----------------------------------------------------
-- View `messenger_db`.`user_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`user_view`;
DROP VIEW IF EXISTS `messenger_db`.`user_view`;
USE `messenger_db`;
create OR REPLACE view user_view as
select bin_to_uuid(u.uuid) as uuid, u.name, a.age, g.gender, l.code
from messenger_db.user as u
         join messenger_db.language as l
              on u.language_id = l.id
         left outer join messenger_db.age_group as a
                         on u.age_id = a.id
         left outer join messenger_db.gender as g
                         on u.gender_id = g.id;

-- -----------------------------------------------------
-- View `messenger_db`.`dialog_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_view`;
DROP VIEW IF EXISTS `messenger_db`.`dialog_view`;
USE `messenger_db`;
create OR REPLACE view dialog_view as
select bin_to_uuid(d.uuid) as uuid, dt.name
from messenger_db.dialog as d
         join messenger_db.dialog_type as dt
              on d.type_id = dt.id;

-- -----------------------------------------------------
-- View `messenger_db`.`dialog_participant_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messenger_db`.`dialog_participant_view`;
DROP VIEW IF EXISTS `messenger_db`.`dialog_participant_view`;
USE `messenger_db`;
create OR REPLACE view dialog_participant_view as
select bin_to_uuid(dialog_uuid) as dialog_uuid, bin_to_uuid(user_uuid) as user_uuid
from dialog_participant;

-- -----------------------------------------------------
-- View `messenger_db`.`message_view`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `messenger_db`.`message_view`;
DROP VIEW IF EXISTS `messenger_db`.`message_view`;
USE `messenger_db`;
create OR REPLACE view `message_view` as
select id, bin_to_uuid(dialog_uuid) as dialog_uuid, bin_to_uuid(user_uuid) as user_uuid, created_at, content
from message;

-- -----------------------------------------------------
-- Fill categories
-- -----------------------------------------------------
INSERT INTO `messenger_db`.`language`
VALUES (1, 'English', 'en');
INSERT INTO `messenger_db`.`language`
VALUES (94, 'Russian', 'ru');
INSERT INTO `messenger_db`.`language`
VALUES (23, 'German', 'de');
INSERT INTO `messenger_db`.`language`
VALUES (34, 'French', 'fr');
INSERT INTO `messenger_db`.`language`
VALUES (51, 'Italian', 'it');
INSERT INTO `messenger_db`.`language`
VALUES (20, 'Czech', 'cs');

INSERT INTO `messenger_db`.`gender`
VALUES (1, 'male');
INSERT INTO `messenger_db`.`gender`
VALUES (2, 'female');

INSERT INTO `messenger_db`.`age_group`
VALUES (1, '14-18');
INSERT INTO `messenger_db`.`age_group`
VALUES (2, '16-20');
INSERT INTO `messenger_db`.`age_group`
VALUES (3, '18-24');
INSERT INTO `messenger_db`.`age_group`
VALUES (4, '22-26');
INSERT INTO `messenger_db`.`age_group`
VALUES (5, '24-30');
INSERT INTO `messenger_db`.`age_group`
VALUES (6, '30+');

INSERT INTO `messenger_db`.`dialog_type`
VALUES (1, 'normal');
INSERT INTO `messenger_db`.`dialog_type`
VALUES (2, 'flirtation');
INSERT INTO `messenger_db`.`dialog_type`
VALUES (3, 'language');

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
